# Generated by Django 4.2.23 on 2025-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoice_layout_preference',
            field=models.CharField(choices=[('classic', 'Classic Layout'), ('traditional', 'Traditional Layout')], default='classic', help_text='Preferred invoice PDF layout format', max_length=20),
        ),
    ]
