# Generated by Django 4.2.7 on 2025-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_invoice_layout_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_store_override',
            field=models.BooleanField(default=True, help_text='Allow stores to override user invoice layout preference'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_default_payment_terms',
            field=models.IntegerField(default=30, help_text='Default payment terms in days (e.g., 30 for Net 30)'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Default GST tax rate percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_number_prefix',
            field=models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV, BILL, TXN)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_number_separator',
            field=models.CharField(default='/', help_text='Separator character for invoice numbers (e.g., /, -, _)', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_reset_frequency',
            field=models.CharField(choices=[('never', 'Never Reset'), ('yearly', 'Reset Yearly'), ('monthly', 'Reset Monthly')], default='yearly', help_text='How often to reset invoice numbering sequence', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_sequence_padding',
            field=models.IntegerField(default=4, help_text='Number of digits for sequence padding (e.g., 4 for 0001)'),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_terms_and_conditions',
            field=models.TextField(blank=True, default='1. Goods once sold will not be taken back.\n2. Interest @ 18% p.a. will be charged on delayed payments.\n3. Subject to jurisdiction only.\n4. All disputes subject to arbitration only.', help_text='Default terms and conditions for invoices', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_validity_days',
            field=models.IntegerField(default=30, help_text='Default invoice validity period in days'),
        ),
    ]
