# Generated by Django 4.2.23 on 2025-08-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_gst_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state_code',
            field=models.CharField(default='10', help_text='GST State Code', max_length=2),
        ),
    ]
