# Generated by Django 4.2.23 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_state_code'),
    ]

    operations = [
        # Company indexes
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='company_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-created_at'], name='company_created_desc_idx'),
        ),
        # Composite index for filtering companies by owner
        migrations.AddIndex(
            model_name='company',
            index=models.Index(
                fields=['owner', 'is_active', 'name'],
                name='company_owner_active_name_idx'
            ),
        ),
    ]
