# Generated by Django 4.2.23 on 2025-11-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_owner_active_name_idx',
        ),
    ]
