# Generated by Django 4.2.23 on 2025-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_company_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company_signatures/'),
        ),
    ]
