# Generated by Django 4.2.23 on 2025-08-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_gst_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms_and_conditions',
            field=models.TextField(default='1. Goods once sold will not be taken back.\n2. Interest @ 18% p.a. will be charged on delayed payments.\n3. Subject to jurisdiction only.\n4. All disputes subject to arbitration only.'),
        ),
    ]
