# Generated by Django 4.2.23 on 2025-08-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(default='', help_text='Place of supply with state name', max_length=100),
        ),
    ]
