# Generated by Django 4.2.23 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_place_of_supply'),
    ]

    operations = [
        # Customer indexes
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['gstin'], name='customer_gstin_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='customer_created_desc_idx'),
        ),
        # Composite index for filtering customers by company
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(
                fields=['company', 'name'],
                name='customer_company_name_idx'
            ),
        ),

        # Invoice indexes
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date'], name='invoice_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='invoice_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoice_created_desc_idx'),
        ),
        # Composite index for filtering invoices by company and status
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['company', 'status', '-created_at'],
                name='invoice_comp_status_date_idx'
            ),
        ),
        # Composite index for customer invoices
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['customer', '-invoice_date'],
                name='invoice_customer_date_idx'
            ),
        ),
        # Composite index for store invoices
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['store', '-created_at'],
                name='invoice_store_created_idx'
            ),
        ),
    ]
