# Generated by Django 4.2.23 on 2025-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_gstin_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_company_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_date_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_comp_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_customer_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_store_created_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.TextField(blank=True, help_text="Invoice-specific billing address (leave blank to use customer's default)", null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='include_logistics',
            field=models.BooleanField(default=False, help_text='Include driver/logistics details in PDF'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lr_number',
            field=models.CharField(blank=True, help_text='Lorry Receipt Number / Transport Document No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
