# Generated by Django 4.2.7 on 2025-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_customer_customer_name_idx_and_more'),
    ]

    operations = [
        # Critical: Composite index for admin users (company + created_at DESC)
        # Optimizes: Invoice.objects.filter(company__owner=user).order_by('-created_at')
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['company', '-created_at'],
                name='invoice_company_created_desc_idx'
            ),
        ),

        # Critical: Composite index for store users (store + created_at DESC)
        # Optimizes: Invoice.objects.filter(store__id__in=stores).order_by('-created_at')
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['store', '-created_at'],
                name='invoice_store_created_desc_idx'
            ),
        ),

        # Important: Index for status filtering
        # Optimizes: Invoice.objects.filter(status='paid')
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['status'],
                name='invoice_status_idx'
            ),
        ),

        # Important: Index for date filtering
        # Optimizes: Invoice.objects.filter(invoice_date=date)
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['invoice_date'],
                name='invoice_date_idx'
            ),
        ),

        # Useful: Standalone index on created_at for fallback
        # Optimizes: Invoice.objects.order_by('-created_at')
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['-created_at'],
                name='invoice_created_desc_idx'
            ),
        ),
    ]
