# Generated by Django 4.2.7 on 2025-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_add_critical_performance_indexes'),
    ]

    operations = [
        # Add index on invoice_number for faster uniqueness checks during generation
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_number_idx'),
        ),
        # Add composite index on store and invoice_date for faster number generation queries
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'invoice_date'], name='invoice_store_date_idx'),
        ),
        # Add index on customer name and company for faster get_or_create lookups
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'company'], name='customer_name_company_idx'),
        ),
    ]
