# Generated by Django 4.2.7 on 2025-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_add_performance_indexes'),
    ]

    operations = [
        # Add composite index on store and created_at for faster user invoice queries
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', '-created_at'], name='invoice_store_created_idx'),
        ),
    ]
