# Generated by Django 4.2.7 on 2025-11-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_add_user_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_name_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_company_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_store_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_store_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_store_created_idx',
        ),
    ]
