# Generated by Django 4.2.23 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        # Store indexes
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='store_name_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city'], name='store_city_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['state'], name='store_state_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['-created_at'], name='store_created_desc_idx'),
        ),
        # Composite index for filtering stores by company
        migrations.AddIndex(
            model_name='store',
            index=models.Index(
                fields=['company', 'is_active', 'name'],
                name='store_company_active_name_idx'
            ),
        ),

        # StoreUser indexes
        migrations.AddIndex(
            model_name='storeuser',
            index=models.Index(fields=['is_active'], name='storeuser_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storeuser',
            index=models.Index(
                fields=['store', 'is_active'],
                name='storeuser_store_active_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='storeuser',
            index=models.Index(
                fields=['user', 'is_active'],
                name='storeuser_user_active_idx'
            ),
        ),
    ]
