# Generated by Django 4.2.23 on 2025-11-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='store',
            name='store_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_company_active_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeuser',
            name='storeuser_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeuser',
            name='storeuser_store_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeuser',
            name='storeuser_user_active_idx',
        ),
    ]
