# Generated by Django 4.2.23 on 2025-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_store_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='invoice_layout_preference',
            field=models.CharField(choices=[('classic', 'Classic Layout'), ('traditional', 'Traditional Layout')], default='traditional', help_text='Invoice PDF layout for all users in this store', max_length=20),
        ),
    ]
