# Generated by Django 4.2.7 on 2025-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_invoice_layout_preference'),
    ]

    operations = [
        # Add composite index on user and is_active for faster store assignment lookups
        migrations.AddIndex(
            model_name='storeuser',
            index=models.Index(fields=['user', 'is_active'], name='storeuser_user_active_idx'),
        ),
        # Add index on store for reverse lookups
        migrations.AddIndex(
            model_name='storeuser',
            index=models.Index(fields=['store', 'is_active'], name='storeuser_store_active_idx'),
        ),
    ]
