# Generated by Django 4.2.7 on 2025-11-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_add_storeuser_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storeuser',
            name='storeuser_user_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeuser',
            name='storeuser_store_active_idx',
        ),
    ]
