# Generated by Claude Code
# Migration to convert Item.company from ForeignKey to ManyToManyField

from django.db import migrations, models


def migrate_company_to_companies(apps, schema_editor):
    """Copy data from company FK to companies M2M"""
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        if item.company_id:  # Check if company exists
            item.companies.add(item.company_id)


def reverse_migration(apps, schema_editor):
    """Reverse migration: copy first company back to company FK"""
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        first_company = item.companies.first()
        if first_company:
            item.company_id = first_company.id
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_state_code'),
        ('items', '0002_inventorytransfer'),
    ]

    operations = [
        # Step 1: Add the new ManyToManyField
        migrations.AddField(
            model_name='item',
            name='companies',
            field=models.ManyToManyField(
                help_text='Companies this item belongs to',
                related_name='items',
                to='companies.company',
                blank=True
            ),
        ),
        # Step 2: Migrate data from company to companies
        migrations.RunPython(
            migrate_company_to_companies,
            reverse_code=reverse_migration
        ),
        # Step 3: Remove the old ForeignKey
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
    ]
