# Generated by Django 4.2.7 on 2025-11-11 10:29
# Modified to add data migration for populating company field

from django.db import migrations, models
import django.db.models.deletion


def populate_company_from_store(apps, schema_editor):
    """Populate company field with store's company for existing records"""
    StoreInventory = apps.get_model('items', 'StoreInventory')
    for inventory in StoreInventory.objects.select_related('store__company').all():
        inventory.company = inventory.store.company
        inventory.save(update_fields=['company'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear company field"""
    StoreInventory = apps.get_model('items', 'StoreInventory')
    StoreInventory.objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('companies', '0003_alter_company_state_code'),
        ('items', '0003_migrate_to_many_to_many_companies'),
    ]

    operations = [
        # Step 1: Remove old unique constraint
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=set(),
        ),
        # Step 2: Add company field as nullable
        migrations.AddField(
            model_name='storeinventory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this inventory entry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='companies.company'),
        ),
        # Step 3: Populate company field from store's company
        migrations.RunPython(
            populate_company_from_store,
            reverse_code=reverse_populate
        ),
        # Step 4: Update Item.companies field (housekeeping)
        migrations.AlterField(
            model_name='item',
            name='companies',
            field=models.ManyToManyField(help_text='Companies this item belongs to', related_name='items', to='companies.company'),
        ),
        # Step 5: Add new unique constraint with company
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('item', 'store', 'company')},
        ),
    ]
