# Generated by Django 4.2.7 on 2025-11-11 16:18

from django.db import migrations, models
import django.db.models.deletion


def populate_transfer_company_from_store(apps, schema_editor):
    """Populate company field with from_store's company for existing transfers"""
    InventoryTransfer = apps.get_model('items', 'InventoryTransfer')
    for transfer in InventoryTransfer.objects.select_related('from_store__company').all():
        transfer.company = transfer.from_store.company
        transfer.save(update_fields=['company'])


def reverse_populate_transfer(apps, schema_editor):
    """Reverse migration - clear company field"""
    InventoryTransfer = apps.get_model('items', 'InventoryTransfer')
    InventoryTransfer.objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_state_code'),
        ('items', '0004_alter_storeinventory_unique_together_and_more'),
    ]

    operations = [
        # Step 1: Make StoreInventory.company non-nullable (it was already populated in 0004)
        migrations.AlterField(
            model_name='storeinventory',
            name='company',
            field=models.ForeignKey(
                help_text='Company this inventory entry belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='store_inventories',
                to='companies.company'
            ),
        ),
        # Step 2: Add InventoryTransfer.company as nullable
        migrations.AddField(
            model_name='inventorytransfer',
            name='company',
            field=models.ForeignKey(
                blank=True,
                help_text='Company this transfer belongs to',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventory_transfers',
                to='companies.company'
            ),
        ),
        # Step 3: Populate InventoryTransfer.company from from_store's company
        migrations.RunPython(
            populate_transfer_company_from_store,
            reverse_code=reverse_populate_transfer
        ),
        # Step 4: Make InventoryTransfer.company non-nullable
        migrations.AlterField(
            model_name='inventorytransfer',
            name='company',
            field=models.ForeignKey(
                help_text='Company this transfer belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventory_transfers',
                to='companies.company'
            ),
        ),
    ]
