# Generated by Django 4.2.23 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_add_company_to_transfer_and_make_fields_required'),
    ]

    operations = [
        # Item indexes
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_name_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='items_active_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='items_created_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_created_desc_idx'),
        ),

        # StoreInventory indexes
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['quantity'], name='inventory_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['min_stock_level'], name='inventory_min_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['last_updated'], name='inventory_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['-last_updated'], name='inventory_updated_desc_idx'),
        ),

        # InventoryTransaction indexes
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='trans_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='trans_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-created_at'], name='trans_created_desc_idx'),
        ),
        # Composite index for filtering transactions by inventory and type
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(
                fields=['inventory', 'transaction_type', '-created_at'],
                name='trans_inv_type_date_idx'
            ),
        ),

        # InventoryTransfer indexes
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['status'], name='transfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['created_at'], name='transfer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['-created_at'], name='transfer_created_desc_idx'),
        ),
        # Composite index for filtering transfers by company and status
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(
                fields=['company', 'status', '-created_at'],
                name='transfer_comp_status_date_idx'
            ),
        ),
    ]
