# Generated by Django 4.2.23 on 2025-11-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_remove_store_store_name_idx_and_more'),
        ('items', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfer_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='trans_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='trans_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='trans_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='trans_inv_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransfer',
            name='transfer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransfer',
            name='transfer_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransfer',
            name='transfer_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransfer',
            name='transfer_comp_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeinventory',
            name='inventory_qty_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeinventory',
            name='inventory_min_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeinventory',
            name='inventory_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeinventory',
            name='inventory_updated_desc_idx',
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_batches', to='stores.store'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_batches', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this transfer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='items.transferbatch'),
        ),
    ]
