# Generated by Django 4.2.23 on 2025-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6, unique=True)),
                ('post_office', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pincodes',
                'ordering': ['pincode'],
                'indexes': [models.Index(fields=['pincode'], name='pincodes_pincode_6e549e_idx'), models.Index(fields=['city'], name='pincodes_city_f449c0_idx'), models.Index(fields=['state'], name='pincodes_state_6adc07_idx')],
            },
        ),
    ]
